#!/bin/bash -e

if [[ $# == 0 ]]; then
	echo "missing config name, usage switch <config name> <optional other args>"
	exit 1
fi

config_name="$1"
shift

function build() {
	nix build \
		--extra-experimental-features 'nix-command flakes' \
		--show-trace \
		--verbose \
		".#$1"
}

case $(uname -o) in
	Darwin)
		build "darwinConfigurations.$config_name.system"

		./result/sw/bin/darwin-rebuild check \
			--show-trace \
			--verbose \
			--flake ".#$config_name" "$@"
		;;
	Linux)

		if [ -f /etc/NIXOS ]; then
			build "nixosConfigurations.$config_name.system"
			sudo nixos-rebuild test \
				--show-trace \
				--flake ".#$config_name" "$@"
		else
			echo "Need to implement/port over linux"
			exit 1
		fi

		;;
	*)
		echo "System type $(uname -o) not supported"
		exit 1
		;;
esac
